### ISSUE TITLE
Huge memory usage

### ISSUE THREAD

**Issue by kant2002** [hacklex/CuteCAS#7] opened 2022-04-17 13:15 UTC
I did attempt to troubleshoot https://github.com/FStarLang/FStar/issues/2539 by running 
```powershell
date ; fstar.exe CuteCAS/Fractions.fst --cache_off --include CuteCAS ; date
```

and notice that FStar.exe start eating memory like crazy, going up to 15Gb with spikes. Other Fstar files from main repo, seems to be not producing this kind of usage. So probably something in your code that make it exponentially blow up.

**Comment by hacklex** [comment] 2022-04-17 14:47
That's because fstar files just do other things and other things just happened to not catch said regression.

Might as well add these files to FStar as a form of test suite; it will ruin the check the moment anyone commits something harmful...

**Comment by hacklex** [comment] 2022-08-10 02:11
Fixed as of now, but the problem lied with the newer versions of F*, and the [problem still remains](https://github.com/FStarLang/FStar/issues/2676).

I'm not sure if I should close this issue yet.

**Closed as completed** 2022-08-10 02:51 UTC
